import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import * as ReportAPI from '../../api/reports.js';

function pct(rate) {
  if (rate === null || rate === undefined) return '0.0%';
  return (rate * 100).toFixed(1) + '%';
}

function fmtHrs(h) {
  if (h === null || h === undefined) return '—';
  return `${h} hrs`;
}

export default function ReportPrintPage() {
  const { id }     = useParams();
  const navigate   = useNavigate();
  const [report,   setReport]  = useState(null);
  const [loading,  setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    ReportAPI.getOne(id)
      .then(res => setReport(res.data.report))
      .catch(err => { if (err.response?.status === 404) setNotFound(true); })
      .finally(() => setLoading(false));
  }, [id]);

  if (loading)  return <div style={ps.center}>Loading report…</div>;
  if (notFound) return <div style={ps.center}>Report not found.</div>;
  if (!report)  return null;

  const summary = report.summary_json;
  const { period, pickups, complaints, generatedAt } = summary;

  return (
    <>
      {/* Print-only styles injected via <style> */}
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { margin: 0; background: #fff; }
          .print-page { padding: 1.5cm 2cm !important; max-width: 100% !important; }
          .print-table { page-break-inside: auto; }
          .print-table tr { page-break-inside: avoid; page-break-after: auto; }
          h2, h3 { page-break-after: avoid; }
          a { text-decoration: none; }
        }
      `}</style>

      <div className="print-page" style={ps.page}>
        {/* Toolbar — hidden on print */}
        <div className="no-print" style={ps.toolbar}>
          <button onClick={() => navigate(-1)} style={ps.backBtn}>← Back</button>
          <button onClick={() => window.print()} style={ps.printBtn}>Print / Save as PDF</button>
        </div>

        {/* Document header */}
        <div style={ps.docHeader}>
          <div style={ps.systemName}>Nairobi Waste Collection Coordination System</div>
          <h1 style={ps.docTitle}>NEMA Performance Report</h1>
          <table style={ps.metaTable}>
            <tbody>
              <tr>
                <td style={ps.metaKey}>Period</td>
                <td style={ps.metaVal}>{period.from} to {period.to}</td>
              </tr>
              <tr>
                <td style={ps.metaKey}>Generated by</td>
                <td style={ps.metaVal}>{report.generated_by_name}</td>
              </tr>
              <tr>
                <td style={ps.metaKey}>Generated on</td>
                <td style={ps.metaVal}>{new Date(generatedAt).toLocaleString()}</td>
              </tr>
            </tbody>
          </table>
          <div style={ps.divider} />
        </div>

        {/* Overall summary */}
        <section style={ps.section}>
          <h2 style={ps.h2}>Overall Summary</h2>
          <div style={ps.summaryGrid}>
            <SummaryItem label="Total pickups"    value={pickups.overall.total} />
            <SummaryItem label="Completed"        value={pickups.overall.completed} />
            <SummaryItem label="Missed"           value={pickups.overall.total - pickups.overall.completed} />
            <SummaryItem label="Completion rate"  value={pct(pickups.overall.completionRate)} />
            <SummaryItem label="Total complaints" value={complaints.overall.total} />
            <SummaryItem label="Resolved"         value={complaints.overall.resolved} />
            <SummaryItem label="Open"             value={complaints.overall.open} />
            <SummaryItem label="Avg resolution"   value={fmtHrs(complaints.overall.avg_resolution_hours)} />
          </div>
        </section>

        {/* Collector performance */}
        <section style={ps.section}>
          <h2 style={ps.h2}>Collector Performance</h2>
          {pickups.byCollector.length === 0 ? (
            <p style={ps.none}>No pickup data for this period.</p>
          ) : (
            <table className="print-table" style={ps.table}>
              <thead>
                <tr>
                  {['Collector', 'Scheduled', 'Completed', 'Missed', 'Completion Rate'].map(h => (
                    <th key={h} style={ps.th}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {pickups.byCollector.map(r => (
                  <tr key={r.collector_id} style={ps.tr}>
                    <td style={{ ...ps.td, fontWeight: 600 }}>{r.company_name}</td>
                    <td style={ps.tdNum}>{r.total}</td>
                    <td style={ps.tdNum}>{r.completed}</td>
                    <td style={ps.tdNum}>{r.missed}</td>
                    <td style={ps.tdNum}>{pct(r.completionRate)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </section>

        {/* Zone performance */}
        <section style={ps.section}>
          <h2 style={ps.h2}>Zone Performance</h2>
          {pickups.byZone.length === 0 ? (
            <p style={ps.none}>No zone data for this period.</p>
          ) : (
            <table className="print-table" style={ps.table}>
              <thead>
                <tr>
                  {['Zone', 'Scheduled', 'Completed', 'Missed', 'Completion Rate', 'Complaints', 'Resolved', 'Avg Resolution'].map(h => (
                    <th key={h} style={ps.th}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {pickups.byZone.map(zp => {
                  const zc = complaints.byZone.find(z => z.zone_id === zp.zone_id) ?? {};
                  return (
                    <tr key={zp.zone_id} style={ps.tr}>
                      <td style={{ ...ps.td, fontWeight: 600 }}>{zp.zone_name}</td>
                      <td style={ps.tdNum}>{zp.total}</td>
                      <td style={ps.tdNum}>{zp.completed}</td>
                      <td style={ps.tdNum}>{zp.missed}</td>
                      <td style={ps.tdNum}>{pct(zp.completionRate)}</td>
                      <td style={ps.tdNum}>{zc.total ?? 0}</td>
                      <td style={ps.tdNum}>{zc.resolved ?? 0}</td>
                      <td style={ps.tdNum}>{fmtHrs(zc.avg_resolution_hours)}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          )}
        </section>

        {/* Complaints by category */}
        {complaints.byCategory?.length > 0 && (
          <section style={ps.section}>
            <h2 style={ps.h2}>Complaints by Category</h2>
            <table className="print-table" style={ps.table}>
              <thead>
                <tr>
                  {['Category', 'Total', 'Resolved', 'Open', 'Avg Resolution'].map(h => (
                    <th key={h} style={ps.th}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {complaints.byCategory.map(r => (
                  <tr key={r.category} style={ps.tr}>
                    <td style={ps.td}>{r.category.replace(/_/g, ' ')}</td>
                    <td style={ps.tdNum}>{r.total}</td>
                    <td style={ps.tdNum}>{r.resolved}</td>
                    <td style={ps.tdNum}>{r.open}</td>
                    <td style={ps.tdNum}>{fmtHrs(r.avg_resolution_hours)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        <div style={ps.footer}>
          This report is a point-in-time snapshot generated on {new Date(generatedAt).toLocaleString()}.
        </div>
      </div>
    </>
  );
}

function SummaryItem({ label, value }) {
  return (
    <div style={ps.summaryItem}>
      <p style={ps.summaryVal}>{value}</p>
      <p style={ps.summaryLabel}>{label}</p>
    </div>
  );
}

const ps = {
  page:        { padding: '2rem 3rem', maxWidth: '960px', margin: '0 auto', background: '#fff', minHeight: '100vh', fontFamily: "'Georgia', serif" },
  center:      { padding: '3rem', textAlign: 'center', color: '#6b7280' },
  toolbar:     { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem', padding: '0.75rem 1rem', background: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: '0.5rem' },
  backBtn:     { padding: '0.4rem 0.9rem', background: 'transparent', border: '1.5px solid #d1d5db', borderRadius: '0.4rem', cursor: 'pointer', fontSize: '0.875rem', fontFamily: 'inherit' },
  printBtn:    { padding: '0.45rem 1.1rem', background: '#16a34a', color: '#fff', border: 'none', borderRadius: '0.45rem', cursor: 'pointer', fontSize: '0.875rem', fontWeight: 600, fontFamily: 'inherit' },
  docHeader:   { marginBottom: '2rem' },
  systemName:  { fontSize: '0.85rem', color: '#6b7280', marginBottom: '0.4rem', textTransform: 'uppercase', letterSpacing: '0.06em' },
  docTitle:    { fontSize: '1.75rem', fontWeight: 700, color: '#111827', margin: '0 0 1rem' },
  metaTable:   { borderCollapse: 'collapse', marginBottom: '1rem' },
  metaKey:     { padding: '0.2rem 1.5rem 0.2rem 0', fontSize: '0.85rem', fontWeight: 700, color: '#374151', verticalAlign: 'top' },
  metaVal:     { padding: '0.2rem 0', fontSize: '0.85rem', color: '#4b5563' },
  divider:     { borderTop: '2px solid #111827', marginTop: '1rem' },
  section:     { marginBottom: '2rem' },
  h2:          { fontSize: '1.1rem', fontWeight: 700, color: '#111827', margin: '0 0 0.75rem', paddingBottom: '0.3rem', borderBottom: '1px solid #e5e7eb' },
  summaryGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '0.75rem' },
  summaryItem: { padding: '0.75rem 1rem', border: '1px solid #e5e7eb', borderRadius: '0.4rem', background: '#f9fafb' },
  summaryVal:  { fontSize: '1.4rem', fontWeight: 700, color: '#111827', margin: '0 0 0.2rem' },
  summaryLabel:{ fontSize: '0.75rem', color: '#6b7280', margin: 0, textTransform: 'uppercase', letterSpacing: '0.04em' },
  table:       { width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' },
  th:          { textAlign: 'left', padding: '0.5rem 0.75rem', fontSize: '0.72rem', fontWeight: 700, color: '#111827', textTransform: 'uppercase', letterSpacing: '0.04em', borderBottom: '2px solid #111827', background: '#f9fafb' },
  tr:          { borderBottom: '1px solid #e5e7eb' },
  td:          { padding: '0.5rem 0.75rem', color: '#1f2937', verticalAlign: 'middle' },
  tdNum:       { padding: '0.5rem 0.75rem', color: '#1f2937', verticalAlign: 'middle', textAlign: 'right' },
  none:        { color: '#9ca3af', fontSize: '0.875rem' },
  footer:      { marginTop: '3rem', paddingTop: '1rem', borderTop: '1px solid #e5e7eb', fontSize: '0.75rem', color: '#9ca3af', textAlign: 'center' },
};
